version: '3.3'

services:
   db:
        image: mysql:5.7
        volumes:
            - mysqldb:/home/btc/mysql
        restart: always
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: TFMUSAIT
            MYSQL_DATABASE: tfm
            MYSQL_USER: alvmarrod
            MYSQL_PASSWORD: alvmarrodtfm

volumes:
    mysqldb: